target:	hw6

hw6:  main.cpp set.cpp array.cpp vector.cpp array.h set.h vector.h iterable.h
	g++ -std=c++11  main.cpp set.cpp array.cpp vector.cpp array.h set.h vector.h iterable.h -o hw6

 clean:
	rm hw6